const COLORS = {
    PRIMARY_BG: '#FF9F0A',
    PRIMARY_TEXT: '#FFFDF7',
    SECONDARY_BG: '#A5A5A5',
    SECONDARY_TEXT: '#030303',
    DEFAULT_BG: '#343434',
    DEFAULT_TEXT: '#F2F2F2',
    RESULT_TEXT: '#FDFDFD',
    ACTIVE_OPERATOR_BG: "#FFFFFF",
    ACTIVE_OPERATOR_TEXT: "#F6AB36",
};
  
export default COLORS;
